# Generated by Django 2.2.8 on 2020-02-23 10:11

from django.db import migrations


def add_default_values(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Team = apps.get_model('team', 'Team')
    UserTeam = apps.get_model('team', 'UserTeam')

    # Create default team
    User = apps.get_model('auth', 'User')
    Team = apps.get_model('team', 'Team')
    team = Team(
        pk=1,
        tem_name='tasking',
        tem_description='Default Team for all users, with admin as user owner',
        tem_owner=User.objects.get(pk=1))
    team.save()

    # Default UserTeam for all users, being the user "admin" and
    # the team "tasking"
    user_team = UserTeam(
        ut_user=User.objects.get(pk=1),
        ut_team=Team.objects.get(pk=1),
    )
    user_team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
