# Generated by Django 2.2.8 on 2020-02-23 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_description', models.TextField()),
                ('cat_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['cat_order'],
            },
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_name', models.CharField(max_length=200)),
                ('imp_description', models.TextField()),
                ('imp_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['imp_order'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_name', models.CharField(max_length=200)),
                ('sta_description', models.TextField()),
                ('sta_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sta_order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsk_name', models.CharField(max_length=200)),
                ('tsk_description', models.TextField(blank=True, null=True)),
                ('tsk_due_date', models.DateField()),
                ('startdate', models.DateField(blank=True, null=True)),
                ('finishdate', models.DateField(blank=True, null=True)),
                ('tsk_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Category')),
                ('tsk_importance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Importance')),
                ('tsk_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Status')),
                ('tsk_team', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
                ('tsk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tsk_due_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(startdate__lte=django.db.models.expressions.F('finishdate')), name='startdate_lte_finishdate'),
        ),
    ]
