# Generated by Django 2.2.8 on 2020-02-08 18:33

from django.db import migrations


def add_default_values(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model('tasks', 'Category')
    Importance = apps.get_model('tasks', 'Importance')
    Status = apps.get_model('tasks', 'Status')

    cat = Category(
        pk=1,
        cat_name='Undefined',
        cat_description='Default Category',
        cat_order=1)
    cat.save()

    imp = Importance(
        pk=1,
        imp_name='Low',
        imp_description='Default Importance',
        imp_order=1)
    imp.save()

    sta = Status(
        pk=1,
        sta_name='Not Started',
        sta_description='Default Status',
        sta_order=1)
    sta.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
