# Generated by Django 2.2.8 on 2020-02-23 10:32

from django.db import migrations


def add_default_values(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical
    # version.
    Category = apps.get_model('tasks', 'Category')
    Importance = apps.get_model('tasks', 'Importance')
    Status = apps.get_model('tasks', 'Status')

    # Categories
    cat1 = Category(
        pk=1,
        cat_name='undefined',
        cat_description='Default Category',
        cat_order=8)
    cat1.save()
    cat2 = Category(
        pk=2,
        cat_name='Undefined',
        cat_description='Default Category',
        cat_order=1)
    cat2.save()
    cat3 = Category(
        pk=3,
        cat_name='meetings',
        cat_description='Meetings Category',
        cat_order=2)
    cat3.save()
    cat4 = Category(
        pk=4,
        cat_name='other',
        cat_description='Other Category',
        cat_order=3)
    cat4.save()
    cat5 = Category(
        pk=5,
        cat_name='planning',
        cat_description='Planning Category',
        cat_order=4)
    cat5.save()
    cat6 = Category(
        pk=6,
        cat_name='projects',
        cat_description='Projects Category',
        cat_order=5)
    cat6.save()
    cat7 = Category(
        pk=7,
        cat_name='training',
        cat_description='Training Category',
        cat_order=6)
    cat7.save()
    cat8 = Category(
        pk=8,
        cat_name='travel',
        cat_description='Travel Category',
        cat_order=7)
    cat8.save()

    # Importances
    imp = Importance(
        pk=1,
        imp_name='low',
        imp_description='Default Importance',
        imp_order=3)
    imp.save()
    imp = Importance(
        pk=2,
        imp_name='medium',
        imp_description='Medium importance',
        imp_order=2)
    imp.save()
    imp = Importance(
        pk=3,
        imp_name='high',
        imp_description='High Importance',
        imp_order=1)
    imp.save()

    # Status
    sta = Status(
        pk=1,
        sta_name='not started',
        sta_description='Default Status',
        sta_order=1)
    sta.save()
    sta = Status(
        pk=2,
        sta_name='started',
        sta_description='Started Status',
        sta_order=2)
    sta.save()
    sta = Status(
        pk=3,
        sta_name='25%',
        sta_description='25% Status',
        sta_order=3)
    sta.save()
    sta = Status(
        pk=4,
        sta_name='50%',
        sta_description='50% Status',
        sta_order=4)
    sta.save()
    sta = Status(
        pk=5,
        sta_name='75%',
        sta_description='75% Status',
        sta_order=5)
    sta.save()
    sta = Status(
        pk=6,
        sta_name='completed',
        sta_description='Completed Status',
        sta_order=6)
    sta.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
