# Generated by Django 2.2.8 on 2020-02-08 18:36

from django.db import migrations
from django.utils import timezone
from django.contrib.auth import get_user_model


def add_default_values(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.

    # Create Superuser
    # https://gist.github.com/inirudebwoy/7eb2d74ea950c38559e5
    super_user = get_user_model()(
        pk=1,
        is_active=True,
        is_superuser=True,
        is_staff=True,
        username='admin',
        email='',
        last_login=timezone.now(),
    )
    super_user.set_password('admin')
    super_user.save()

    # Create default team
    User = apps.get_model('auth', 'User')
    Team = apps.get_model('tasks', 'Team')
    team = Team(
        pk=1,
        tem_name='tasking',
        tem_description='Default Team with user owner Admin',
        tem_owner=User.objects.get(pk=1))
    team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200208_1833'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
