# Generated by Django 2.2.8 on 2020-02-07 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsk_name', models.CharField(max_length=200)),
                ('tsk_description', models.TextField(blank=True, null=True)),
                ('tsk_due_date', models.DateField()),
                ('startdate', models.DateField(blank=True, null=True)),
                ('finishdate', models.DateField(blank=True, null=True)),
                ('tsk_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Category')),
                ('tsk_grp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Group')),
                ('tsk_importance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Importance')),
                ('tsk_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tsk_due_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(startdate__lt=django.db.models.expressions.F('finishdate')), name='startdate_lt_finishdate'),
        ),
    ]
