# Generated by Django 2.2.8 on 2020-02-08 19:28

from django.db import migrations


def add_default_values(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Team = apps.get_model('tasks', 'Team')
    User = apps.get_model('auth', 'User')
    UserTeam = apps.get_model('tasks', 'UserTeam')

    # Default user (admin) and team (tasking)
    user_team = UserTeam(
        ut_user=User.objects.get(pk=1),
        ut_team=Team.objects.get(pk=1),
    )
    user_team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200208_1836'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
