# Generated by Django 2.2.8 on 2020-02-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200208_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='tsk_user',
        ),
    ]
