# Generated by Django 2.2.8 on 2020-02-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200207_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='ug_group',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='ug_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tsk_grp',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
