# Generated by Django 2.2.8 on 2020-02-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200209_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userteam',
            options={'ordering': ['ut_team']},
        ),
    ]
