# Generated by Django 2.2.8 on 2020-02-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200207_0955'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userteam',
            name='user_team',
        ),
        migrations.AddConstraint(
            model_name='userteam',
            constraint=models.UniqueConstraint(fields=('ut_user', 'ut_team'), name='user_team'),
        ),
    ]
