# Generated by Django 2.2.8 on 2020-02-12 01:13

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200209_0300'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='startdate_lt_finishdate',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(startdate__lte=django.db.models.expressions.F('finishdate')), name='startdate_lte_finishdate'),
        ),
    ]
