# Generated by Django 2.2.8 on 2020-02-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200207_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTeam',
        ),
    ]
