# Generated by Django 2.2.8 on 2020-02-07 17:24

from django.db import migrations


def add_default_values(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Team = apps.get_model('tasks', 'Team')
    User = apps.get_model('auth', 'User')

    team = Team(
        pk=1,
        tem_name='tasking',
        tem_description='Default Team with user owner Admin',
        tem_owner=User.objects.get(pk=1))
    team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200207_1001'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
